version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8082:8080

  redis:
    image: redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 30
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./docker-data/redis:/data

  redis_insight:
    image: redislabs/redisinsight
    container_name: redis_insight
    ports:
      - 8001:5540
    volumes:
      - ./docker-data/redis_insight:/data
